import * as XLSX from "xlsx";
import { List } from "reselect/es/types";
import { BTDeviceDto } from "../../services/bt_device_service";
import { format, parseISO } from "date-fns";

export function handleGenerateBTDeviceExcel(datas: List<BTDeviceDto>) {
  // Create a new workbook
  const workbook = XLSX.utils.book_new();

  const worksheet = XLSX.utils.aoa_to_sheet([
    [
      "Device Code",
      "Power PCB Code",
      "Power PCB Code Status",
      "Pump Code",
      "Pump Code Status",
      "Fan Code",
      "Fan Code Status",
      "UI PCB Code",
      "UI PCB Code Status",
      "Encoder Code",
      "Encoder Code Status",
      "Main PCB Code",
      "Main PCB Code Status",
      "Manifold Code",
      "Manifold Code Status",
      "Valve Card Inside Cable Set Code",
      "Valve Card Inside Cable Set Code Status",
      "Valve Card Input Output Cable Set Code",
      "Valve Card Input Output Cable Set Code Status",
      "Over Pressure Valve Code",
      "Over Pressure Valve Code Status",
      "Power Cable Code",
      "UI Cable Code",
      "Display Code",
      "Front Bracket Assembly Code",
      "Front Bracket Assembly Code Status",
      "Power Adaptor Code",
      "Power Adaptor Code Status",
      "Enclosure Top Code",
      "Enclosure Bottom Code",
      "Back Vent Code",
      "Fan Mount Code",
      "Encoder Supporter Code",
      "PCB Holder Code",
      "Valve Card One",
      "Valve Card Two",
      "Valve Card Three",
      "Valve Card Four",
      "Valve Card Five",
      "Valve Card Six",
      "Valve Card Seven",
      "Valve Card Eight",
      "Created By",
      "Date Time",
    ],
    ...datas.map((data) => [
      data.deviceCode,
      data.powerPcbCode,
      data.powerPcbCodeStatus,
      data.pumpCode,
      data.pumpCodeStatus,
      data.fanCode,
      data.fanCodeStatus,
      data.uiPcbCode,
      data.uiPcbCodeStatus,
      data.encoderCode,
      data.encoderCodeStatus,
      data.mainPcbCode,
      data.mainPcbCodeStatus,
      data.manifoldCode,
      data.manifoldCodeStatus,
      data.valveCardInsideCableSetCode,
      data.valveCardInsideCableSetCodeStatus,
      data.valveCardInputOutputCableSetCode,
      data.valveCardInputOutputCableSetCodeStatus,
      data.overPressureValveCode,
      data.overPressureValveCodeStatus,
      data.powerCableCode,
      data.uiCableCode,
      data.displayCode,
      data.frontBracketAssemblyCode,
      data.frontBracketAssemblyCodeStatus,
      data.powerAdaptorCode,
      data.powerAdaptorCodeStatus,
      data.enclosureTopCode,
      data.enclosureBottomCode,
      data.backVentCode,
      data.fanMountCode,
      data.encoderSupporterCode,
      data.pcbHolderCode,
      data.valveCards.length > 0 ? data.valveCards[0] : "",
      data.valveCards.length > 1 ? data.valveCards[1] : "",
      data.valveCards.length > 2 ? data.valveCards[2] : "",
      data.valveCards.length > 3 ? data.valveCards[3] : "",
      data.valveCards.length > 4 ? data.valveCards[4] : "",
      data.valveCards.length > 5 ? data.valveCards[5] : "",
      data.valveCards.length > 6 ? data.valveCards[6] : "",
      data.valveCards.length > 7 ? data.valveCards[7] : "",
      data.createdBy,
      format(parseISO(data.dateTime), "yyyy-MM-dd HH:mm:ss"),
    ]),
  ]);

  // Add the worksheet to the workbook
  XLSX.utils.book_append_sheet(workbook, worksheet, "Sheet1");

  // Save the workbook as an Excel file
  XLSX.writeFile(workbook, "BT_Device_" + new Date().toISOString() + ".xlsx");
}
