import * as XLSX from "xlsx";
import { format, parseISO } from "date-fns";

export function handleGenerateValveExcel(datas: any[]) {

  const workbook = XLSX.utils.book_new();

  const worksheet = XLSX.utils.aoa_to_sheet([
    [
      "Serial Number",
      "Physical Inspection State",
      "Manifold Seal Pressure",
      "Manifold Pressure After 1 Sec",
      "Manifold Pressure State",
      "Valve 1 Inflation Pressure",
      "Valve 1 State",
      "Valve 3 Inflation Pressure",
      "Valve 3 State",
      "Valve 5 Inflation Pressure",
      "Valve 5 State",
      "Valve 7 Inflation Pressure",
      "Valve 7 State",
      "Valve 9 Inflation Pressure",
      "Valve 9 State",
      "Valve 11 Inflation Pressure",
      "Valve 11 State",
      "Valve 13 Inflation Pressure",
      "Valve 13 State",
      "Valve 15 Inflation Pressure",
      "Valve 15 State",
      "Valve 17 Inflation Pressure",
      "Valve 17 State",
      "Valve 19 Inflation Pressure",
      "Valve 19 State",
      "Valve 21 Inflation Pressure",
      "Valve 21 State",
      "Valve 23 Inflation Pressure",
      "Valve 23 State",
      "Valve 25 Inflation Pressure",
      "Valve 25 State",
      "Valve 27 Inflation Pressure",
      "Valve 27 State",
      "Valve 29 Inflation Pressure",
      "Valve 29 State",
      "Valve 31 Inflation Pressure",
      "Valve 31 State",
      "Valve 33 Inflation Pressure",
      "Valve 33 State",
      "Valve 35 Inflation Pressure",
      "Valve 35 State",
      "Valve 37 Inflation Pressure",
      "Valve 37 State",
      "Valve 39 Inflation Pressure",
      "Valve 39 State",
      "Valve 41 Inflation Pressure",
      "Valve 41 State",
      "Valve 43 Inflation Pressure",
      "Valve 43 State",
      "Valve 45 Inflation Pressure",
      "Valve 45 State",
      "Valve 47 Inflation Pressure",
      "Valve 47 State",
      "Valve 49 Inflation Pressure",
      "Valve 49 State",
      "Valve 51 Inflation Pressure",
      "Valve 51 State",
      "Valve 53 Inflation Pressure",
      "Valve 53 State",
      "Valve 55 Inflation Pressure",
      "Valve 55 State",
      "Valve 57 Inflation Pressure",
      "Valve 57 State",
      "Valve 59 Inflation Pressure",
      "Valve 59 State",
      "Valve 61 Inflation Pressure",
      "Valve 61 State",
      "Valve 63 Inflation Pressure",
      "Valve 63 State",
      "Valve 2 Deflation Pressure",
      "Valve 2 State",
      "Valve 4 Deflation Pressure",
      "Valve 4 State",
      "Valve 6 Deflation Pressure",
      "Valve 6 State",
      "Valve 8 Deflation Pressure",
      "Valve 8 State",
      "Valve 10 Deflation Pressure",
      "Valve 10 State",
      "Valve 12 Deflation Pressure",
      "Valve 12 State",
      "Valve 14 Deflation Pressure",
      "Valve 14 State",
      "Valve 16 Deflation Pressure",
      "Valve 16 State",
      "Valve 18 Deflation Pressure",
      "Valve 18 State",
      "Valve 20 Deflation Pressure",
      "Valve 20 State",
      "Valve 22 Deflation Pressure",
      "Valve 22 State",
      "Valve 24 Deflation Pressure",
      "Valve 24 State",
      "Valve 26 Deflation Pressure",
      "Valve 26 State",
      "Valve 28 Deflation Pressure",
      "Valve 28 State",
      "Valve 30 Deflation Pressure",
      "Valve 30 State",
      "Valve 32 Deflation Pressure",
      "Valve 32 State",
      "Valve 34 Deflation Pressure",
      "Valve 34 State",
      "Valve 36 Deflation Pressure",
      "Valve 36 State",
      "Valve 38 Deflation Pressure",
      "Valve 38 State",
      "Valve 40 Deflation Pressure",
      "Valve 40 State",
      "Valve 42 Deflation Pressure",
      "Valve 42 State",
      "Valve 44 Deflation Pressure",
      "Valve 44 State",
      "Valve 46 Deflation Pressure",
      "Valve 46 State",
      "Valve 48 Deflation Pressure",
      "Valve 48 State",
      "Valve 50 Deflation Pressure",
      "Valve 50 State",
      "Valve 52 Deflation Pressure",
      "Valve 52 State",
      "Valve 54 Deflation Pressure",
      "Valve 54 State",
      "Valve 56 Deflation Pressure",
      "Valve 56 State",
      "Valve 58 Deflation Pressure",
      "Valve 58 State",
      "Valve 60 Deflation Pressure",
      "Valve 60 State",
      "Valve 62 Deflation Pressure",
      "Valve 62 State",
      "Valve 64 Deflation Pressure",
      "Valve 64 State",
      "Overall Valve Sequence State",
      "Status",
      "Date Time"

    ],
    ...datas.map((data) => [
      data.serialNumber,
      data.physicalInspectionState ? "Pass" : "Fail",
      data.manifoldSealPressure,
      data.manifoldPressureAfter1Sec,
      data.manifoldPressureState ? "Pass" : "Fail",
      data.valve1InflationPressure,
      data.valve1State ? "Pass" : "Fail",
      data.valve3InflationPressure,
      data.valve3State ? "Pass" : "Fail",
      data.valve5InflationPressure,
      data.valve5State ? "Pass" : "Fail",
      data.valve7InflationPressure,
      data.valve7State ? "Pass" : "Fail",
      data.valve9InflationPressure,
      data.valve9State ? "Pass" : "Fail",
      data.valve11InflationPressure,
      data.valve11State ? "Pass" : "Fail",
      data.valve13InflationPressure,
      data.valve13State ? "Pass" : "Fail",
      data.valve15InflationPressure,
      data.valve15State ? "Pass" : "Fail",
      data.valve17InflationPressure,
      data.valve17State ? "Pass" : "Fail",
      data.valve19InflationPressure,
      data.valve19State ? "Pass" : "Fail",
      data.valve21InflationPressure,
      data.valve21State ? "Pass" : "Fail",
      data.valve23InflationPressure,
      data.valve23State ? "Pass" : "Fail",
      data.valve25InflationPressure,
      data.valve25State ? "Pass" : "Fail",
      data.valve27InflationPressure,
      data.valve27State ? "Pass" : "Fail",
      data.valve29InflationPressure,
      data.valve29State ? "Pass" : "Fail",
      data.valve31InflationPressure,
      data.valve31State ? "Pass" : "Fail",
      data.valve33InflationPressure,
      data.valve33State ? "Pass" : "Fail",
      data.valve35InflationPressure,
      data.valve35State ? "Pass" : "Fail",
      data.valve37InflationPressure,
      data.valve37State ? "Pass" : "Fail",
      data.valve39InflationPressure,
      data.valve39State ? "Pass" : "Fail",
      data.valve41InflationPressure,
      data.valve41State ? "Pass" : "Fail",
      data.valve43InflationPressure,
      data.valve43State ? "Pass" : "Fail",
      data.valve45InflationPressure,
      data.valve45State ? "Pass" : "Fail",
      data.valve47InflationPressure,
      data.valve47State ? "Pass" : "Fail",
      data.valve49InflationPressure,
      data.valve49State ? "Pass" : "Fail",
      data.valve51InflationPressure,
      data.valve51State ? "Pass" : "Fail",
      data.valve53InflationPressure,
      data.valve53State ? "Pass" : "Fail",
      data.valve55InflationPressure,
      data.valve55State ? "Pass" : "Fail",
      data.valve57InflationPressure,
      data.valve57State ? "Pass" : "Fail",
      data.valve59InflationPressure,
      data.valve59State ? "Pass" : "Fail",
      data.valve61InflationPressure,
      data.valve61State ? "Pass" : "Fail",
      data.valve63InflationPressure,
      data.valve63State ? "Pass" : "Fail",
      data.valve2DeflationPressure,
      data.valve2State ? "Pass" : "Fail",
      data.valve4DeflationPressure,
      data.valve4State ? "Pass" : "Fail",
      data.valve6DeflationPressure,
      data.valve6State ? "Pass" : "Fail",
      data.valve8DeflationPressure,
      data.valve8State ? "Pass" : "Fail",
      data.valve10DeflationPressure,
      data.valve10State ? "Pass" : "Fail",
      data.valve12DeflationPressure,
      data.valve12State ? "Pass" : "Fail",
      data.valve14DeflationPressure,
      data.valve14State ? "Pass" : "Fail",
      data.valve16DeflationPressure,
      data.valve16State ? "Pass" : "Fail",
      data.valve18DeflationPressure,
      data.valve18State ? "Pass" : "Fail",
      data.valve20DeflationPressure,
      data.valve20State ? "Pass" : "Fail",
      data.valve22DeflationPressure,
      data.valve22State ? "Pass" : "Fail",
      data.valve24DeflationPressure,
      data.valve24State ? "Pass" : "Fail",
      data.valve26DeflationPressure,
      data.valve26State ? "Pass" : "Fail",
      data.valve28DeflationPressure,
      data.valve28State ? "Pass" : "Fail",
      data.valve30DeflationPressure,
      data.valve30State ? "Pass" : "Fail",
      data.valve32DeflationPressure,
      data.valve32State ? "Pass" : "Fail",
      data.valve34DeflationPressure,
      data.valve34State ? "Pass" : "Fail",
      data.valve36DeflationPressure,
      data.valve36State ? "Pass" : "Fail",
      data.valve38DeflationPressure,
      data.valve38State ? "Pass" : "Fail",
      data.valve40DeflationPressure,
      data.valve40State ? "Pass" : "Fail",
      data.valve42DeflationPressure,
      data.valve42State ? "Pass" : "Fail",
      data.valve44DeflationPressure,
      data.valve44State ? "Pass" : "Fail",
      data.valve46DeflationPressure,
      data.valve46State ? "Pass" : "Fail",
      data.valve48DeflationPressure,
      data.valve48State ? "Pass" : "Fail",
      data.valve50DeflationPressure,
      data.valve50State ? "Pass" : "Fail",
      data.valve52DeflationPressure,
      data.valve52State ? "Pass" : "Fail",
      data.valve54DeflationPressure,
      data.valve54State ? "Pass" : "Fail",
      data.valve56DeflationPressure,
      data.valve56State ? "Pass" : "Fail",
      data.valve58DeflationPressure,
      data.valve58State ? "Pass" : "Fail",
      data.valve60DeflationPressure,
      data.valve60State ? "Pass" : "Fail",
      data.valve62DeflationPressure,
      data.valve62State ? "Pass" : "Fail",
      data.valve64DeflationPressure,
      data.valve64State ? "Pass" : "Fail",
      data.overallValveSequenceState ? "Pass" : "Fail",
      data.status && data.status ? "Pass" : "Fail",
      format(parseISO(data.dateTime), "yyyy-MM-dd HH:mm:ss"),
    ]),
  ]);

  // Add the worksheet to the workbook
  XLSX.utils.book_append_sheet(workbook, worksheet, "Sheet1");

  // Save the workbook as an Excel file
  XLSX.writeFile(workbook, "Sequence_Valve_Test_" + new Date().toISOString() + ".xlsx");
}
