import * as XLSX from "xlsx";
import { List } from "reselect/es/types";
import { PcbTest } from "../../../services/pcb_test_service";

export function handleGeneratePcbTestExcel(datas: List<PcbTest>) {
  // Create a new workbook
  const workbook = XLSX.utils.book_new();

  const worksheet = XLSX.utils.aoa_to_sheet([
    [
      "Test ID",
      "Serial Number",
      "Charge Port Connection Status",
      "Intensity Button Status",
      "Run Pause Button Status",
      "Mode Button Status",
      "Green Led Status",
      "Blue Led Status",
      "Red Led Ring Status",
      "Green Led Ring Status",
      "Blue Led Ring Status",
      "White Led Ring Status",
      "Led Ring Off Status",
      "Buzzer Status",
      "Latch Switch Led On Status",
      "Latch Switch Off Status",
      "Latch Switch Led Off Status",
      "Latch Switch On Status",
      "Charger Port Disconnect Status",
      "Pump Status",
      "Battery Charging Status",
      "Start Battery Charging Percentage",
      "End Battery Charging Percentage",
      "Battery Temperature Status",
      "Battery Temperature",
      "Pressure Path Status",
      "Start Pressure Path Value",
      "End Pressure Path Value",
      "Pressure Sensor Status",
      "Start Pressure Sensor Value",
      "End Pressure Sensor Value",
      "Valve 01 Status",
      "Valve 01 Start Value",
      "Valve 01 End Value",
      "Valve 02 Status",
      "Valve 02 Start Value",
      "Valve 02 End Value",
      "Valve 03 Status",
      "Valve 03 Start Value",
      "Valve 03 End Value",
      "Valve 04 Status",
      "Valve 04 Start Value",
      "Valve 04 End Value",
      "Valve 05 Status",
      "Valve 05 Start Value",
      "Valve 05 End Value",
      "Valve 06 Status",
      "Valve 06 Start Value",
      "Valve 06 End Value",
      "Phase Two Valve 01 Status",
      "Phase Two Valve 01 Start Value",
      "Phase Two Valve 01 End Value",
      "Phase Two Valve 02 Status",
      "Phase Two Valve 02 Start Value",
      "Phase Two Valve 02 End Value",
      "Phase Two Valve 03 Status",
      "Phase Two Valve 03 Start Value",
      "Phase Two Valve 03 End Value",
      "Phase Two Valve 04 Status",
      "Phase Two Valve 04 Start Value",
      "Phase Two Valve 04 End Value",
      "Phase Two Valve 05 Status",
      "Phase Two Valve 05 Start Value",
      "Phase Two Valve 05 End Value",
      "Phase Two Valve 06 Status",
      "Phase Two Valve 06 Start Value",
      "Phase Two Valve 06 End Value",
      "Phase Two Pressure Sensor Status",
      "Phase Two Pump Status",
      "Status",
      "Date Time"
    ],
    ...datas.map((data) => [
      data.testId,
      data.serialNumber,
      data.chargePortConnectStatus ? "Pass" : "Fail",
      data.intensityButtonStatus ? "Pass" : "Fail",
      data.runPauseButtonStatus ? "Pass" : "Fail",
      data.modeButtonStatus ? "Pass" : "Fail",
      data.greenLedStatus ? "Pass" : "Fail",
      data.blueLedStatus ? "Pass" : "Fail",
      data.redLedRingStatus ? "Pass" : "Fail",
      data.greenLedRingStatus ? "Pass" : "Fail",
      data.blueLedRingStatus ? "Pass" : "Fail",
      data.whiteLedRingStatus ? "Pass" : "Fail",
      data.ledRingOffStatus ? "Pass" : "Fail",
      data.buzzerStatus ? "Pass" : "Fail",
      data.latchSwitchLedOnStatus ? "Pass" : "Fail",
      data.latchSwitchOffStatus ? "Pass" : "Fail",
      data.latchSwitchLedOffStatus ? "Pass" : "Fail",
      data.latchSwitchOnStatus ? "Pass" : "Fail",
      data.chargerPortDisconnectStatus ? "Pass" : "Fail",
      data.pumpStatus ? "Pass" : "Fail",
      data.batteryChargingStatus ? "Pass" : "Fail",
      data.startBatteryChargingPercentage,
      data.endBatteryChargingPercentage,
      data.batteryTemperatureStatus ? "Pass" : "Fail",
      data.batteryTemperature,
      data.pressurePathStatus ? "Pass" : "Fail",
      data.startPressurePathValue,
      data.endPressurePathValue,
      data.pressureSensorStatus ? "Pass" : "Fail",
      data.startPressureSensorValue,
      data.endPressureSensorValue,
      data.valve01Status ? "Pass" : "Fail",
      data.valve01StartValue,
      data.valve01EndValue,
      data.valve02Status ? "Pass" : "Fail",
      data.valve02StartValue,
      data.valve02EndValue,
      data.valve03Status ? "Pass" : "Fail",
      data.valve03StartValue,
      data.valve03EndValue,
      data.valve04Status ? "Pass" : "Fail",
      data.valve04StartValue,
      data.valve04EndValue,
      data.valve05Status ? "Pass" : "Fail",
      data.valve05StartValue,
      data.valve05EndValue,
      data.valve06Status ? "Pass" : "Fail",
      data.valve06StartValue,
      data.valve06EndValue,
      data.phaseTwoValve01Status ? "Pass" : "Fail",
      data.phaseTwoValve01StartValue,
      data.phaseTwoValve01EndValue,
      data.phaseTwoValve02Status ? "Pass" : "Fail",
      data.phaseTwoValve02StartValue,
      data.phaseTwoValve02EndValue,
      data.phaseTwoValve03Status ? "Pass" : "Fail",
      data.phaseTwoValve03StartValue,
      data.phaseTwoValve03EndValue,
      data.phaseTwoValve04Status ? "Pass" : "Fail",
      data.phaseTwoValve04StartValue,
      data.phaseTwoValve04EndValue,
      data.phaseTwoValve05Status ? "Pass" : "Fail",
      data.phaseTwoValve05StartValue,
      data.phaseTwoValve05EndValue,
      data.phaseTwoValve06Status ? "Pass" : "Fail",
      data.phaseTwoValve06StartValue,
      data.phaseTwoValve06EndValue,
      data.phaseTwoPressureSensorStatus ? "Pass" : "Fail",
      data.phaseTwoPumpStatus ? "Pass" : "Fail",
      data.status,
      data.dateTime.split("T").join(" ")
    ]),
  ]);

  // Add the worksheet to the workbook
  XLSX.utils.book_append_sheet(workbook, worksheet, "Sheet1");

  // Save the workbook as an Excel file
  XLSX.writeFile(workbook, "Pcb_Test_" + new Date().toISOString() + ".xlsx");
}
