<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.3.1</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.wave_tech</groupId>
	<artifactId>test_biotab_server</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>test_biotab_server</name>
	<description>Demo project for Spring Boot</description>
	<url/>
	<licenses>
		<license/>
	</licenses>
	<developers>
		<developer/>
	</developers>
	<scm>
		<connection/>
		<developerConnection/>
		<tag/>
		<url/>
	</scm>
	<properties>
		<java.version>21</java.version>
		<jwt.version>0.12.5</jwt.version>
		<jsw.assemble.dir>target/generated-resources/appassembler/jsw</jsw.assemble.dir>
		<appassembler.basedir>target/generated-resources/appassembler/jsw/test_biotab_server</appassembler.basedir>
		<resource.file.location>.</resource.file.location>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>
		<dependency>
			<groupId>com.mysql</groupId>
			<artifactId>mysql-connector-j</artifactId>
			<version>8.2.0</version>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-api</artifactId>
			<version>${jwt.version}</version>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-impl</artifactId>
			<version>${jwt.version}</version>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-jackson</artifactId>
			<version>${jwt.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>repackage</id>
						<phase>none</phase>
					</execution>
				</executions>
				<configuration>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.11.0</version>
				<configuration>
					<source>${java.version}</source>
					<target>${java.version}</target>
					<annotationProcessorPaths>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>${lombok.version}</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>appassembler-maven-plugin</artifactId>
				<version>1.10</version>
				<executions>
					<execution>
						<id>generate-jsw-scripts</id>
						<phase>package</phase>
						<goals>
							<goal>generate-daemons</goal>
							<goal>create-repository</goal>
						</goals>
						<configuration>
							<repositoryLayout>flat</repositoryLayout>
							<configurationDirectory>conf</configurationDirectory>
							<useWildcardClassPath>true</useWildcardClassPath>
							<daemons>
								<daemon>
									<id>test_biotab_server</id>
									<wrapperMainClass>org.tanukisoftware.wrapper.WrapperSimpleApp</wrapperMainClass>
									<mainClass>
										com.test_biotab.test_biotab_server.TestJigServerApplication
									</mainClass>
									<commandLineArguments>
										<commandLineArgument>start</commandLineArgument>
									</commandLineArguments>
									<platforms>
										<platform>jsw</platform>
									</platforms>
									<generatorConfigurations>
										<generatorConfiguration>
											<generator>jsw</generator>
											<configuration>
												<property>
													<name>wrapper.java.additional.1</name>
													<value>-XX:MaxDirectMemorySize=256M</value>
												</property>
												<property>
													<name>configuration.directory.in.classpath.first</name>
													<value>conf</value>
												</property>
												<property>
													<name>set.default.REPO_DIR</name>
													<value>lib</value>
												</property>
												<property>
													<name>wrapper.logfile</name>
													<value>logs/wrapper.log</value>
												</property>
												<property>
													<name>wrapper.startup.timeout</name>
													<value>0</value>
												</property>
												<property>
													<name>wrapper.ping.timeout</name>
													<value>60</value>
												</property>
											</configuration>
											<includes>
												<include>linux-x86-64</include>
											</includes>
										</generatorConfiguration>
									</generatorConfigurations>
								</daemon>
							</daemons>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-antrun-plugin</artifactId>
				<version>1.6</version>
				<executions>
					<execution>
						<id>make-log-dir</id>
						<phase>package</phase>
						<configuration>
							<tasks>
								<mkdir dir="${appassembler.basedir}/logs"/>
								<mkdir dir="target/test_biotab_server/logs"/>

								<copy todir="target/test_biotab_server/bin" overwrite="true">
									<fileset dir="${jsw.assemble.dir}/test_biotab_server/bin"/>
								</copy>
								<copy todir="target/test_biotab_server/lib" overwrite="true">
									<fileset dir="${jsw.assemble.dir}/test_biotab_server/lib"/>
								</copy>
								<copy todir="target/test_biotab_server/lib" overwrite="true">
									<fileset dir="${jsw.assemble.dir}/test_biotab_server/lib"/>
								</copy>
								<copy todir="target/test_biotab_server/conf">
									<fileset dir="${jsw.assemble.dir}/test_biotab_server/conf"/>
								</copy>
								<copy todir="target/test_biotab_server/conf" overwrite="true">
									<fileset dir="src/main/${resource.file.location}/resources"/>
									<filterset>
										<filter token="VERSION" value="${project.version}"/>
									</filterset>
								</copy>
								<chmod dir="target/test_biotab_server/bin" perm="777" includes="**/**"/>
							</tasks>
						</configuration>
						<goals>
							<goal>run</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

</project>
